/**
 * Local data runner — lets Claude Code pull/refresh `hiveku-data/` ITSELF,
 * without the extension in the loop and without routing row data through the
 * model: a generated `.hiveku/pull-data.mjs` executes `hiveku-data/manifest.json`
 * (serialized from the deptData registry) against the account's MCP endpoint.
 *
 * Division of labor (the anti-drift contract):
 *   - manifest.json  = WHAT to pull (tools, args, windows, scope chains) —
 *     regenerated from deptData.DEPARTMENTS on every scaffold/export.
 *   - pull-data.mjs  = HOW to pull (MCP protocol, fan-out, file shapes) —
 *     generic and dataset-agnostic; overwritten on every regeneration
 *     (version-stamped, never hand-edited).
 *
 * Output shapes are byte-compatible with dataExport.ts so the extension and the
 * runner can refresh the same files interchangeably.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { dataManifest } from './deptData';
import { hivekuUserAgent } from './hivekuUserAgent';

// v3: the MCP client below is now a faithful port of src/mcpClient.ts — one
// edge-length budget instead of a fixed 90s guess, the timer held through the
// body read, and a one-shot 429 retry that waits as long as the server asked.
// Bumped so a folder's STATUS.json says which runner actually wrote it.
// v4: every request identifies as Hiveku (HivekuDataRunner/<extension version>),
// baked in at write time because this script runs outside the extension host.
// v5: `account` is a target, and every run except --dataset refreshes the
// read-only hiveku-data/account/ACCOUNT_MEMORY.md (same bytes as the extension
// and the plugin) and records it in STATUS.json the way the plugin does
// (`account_memory`, and a `failed` entry while the read fails). `failed` is now
// computed from the per-department blocks (it read top-level keys and was
// always empty) and keeps the entries of departments this run did not touch.
export const RUNNER_VERSION = 5;
export const RUNNER_REL_PATH = path.join('.hiveku', 'pull-data.mjs');

/**
 * Write (or refresh) the runner + manifest into an account folder.
 * When `defaultDeptIds` is omitted (e.g. a partial department download), the
 * EXISTING manifest's default_departments are preserved — a one-department
 * export must not narrow what --default/--stale pull. Only the scaffold (which
 * knows the role) passes explicit defaults.
 */
export async function writeDataRunner(baseDir: string, defaultDeptIds?: string[]): Promise<void> {
  const manifestFile = path.join(baseDir, 'hiveku-data', 'manifest.json');
  let defaults = defaultDeptIds;
  if (!defaults) {
    try {
      const prev = JSON.parse(await fs.readFile(manifestFile, 'utf8')) as { default_departments?: string[] };
      if (Array.isArray(prev.default_departments) && prev.default_departments.length) defaults = prev.default_departments;
    } catch {
      /* no prior manifest — dataManifest falls back to all departments */
    }
  }
  const manifest = dataManifest(defaults);
  await fs.mkdir(path.join(baseDir, 'hiveku-data'), { recursive: true });
  await fs.writeFile(manifestFile, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  await fs.mkdir(path.join(baseDir, '.hiveku'), { recursive: true });
  await fs.writeFile(path.join(baseDir, RUNNER_REL_PATH), runnerScript(), 'utf8');
}

/**
 * The generated script. Codegen discipline: every backslash that must reach the
 * file is written `\\`; the script itself avoids backtick templates so it can
 * never be confused with this template's own syntax.
 */
function runnerScript(): string {
  return `#!/usr/bin/env node
// Hiveku data runner v${RUNNER_VERSION} — GENERATED by the Hiveku VS Code extension. Do not edit
// (regenerated on every scaffold/export). Pulls account department data into
// hiveku-data/<dept>/ so Claude Code can work on LOCAL files instead of live calls.
//
// Usage (run from anywhere inside the account folder):
//   node .hiveku/pull-data.mjs seo ppc          pull specific departments
//   node .hiveku/pull-data.mjs --default        pull your role's departments
//   node .hiveku/pull-data.mjs --all            pull every department
//   node .hiveku/pull-data.mjs --stale 12       pull default departments older than N hours (default 12)
//   node .hiveku/pull-data.mjs --dataset ppc:campaigns   refresh ONE dataset (e.g. after a write)
//   node .hiveku/pull-data.mjs --list           departments + local freshness
//   node .hiveku/pull-data.mjs account          refresh only the account memory copy
//
// Every run except --dataset also refreshes hiveku-data/account/ACCOUNT_MEMORY.md,
// a READ-ONLY copy of the account memory: owners and admins edit it on the Hiveku
// dashboard, and nothing uploads this file.
//
// Reads the account MCP endpoint + key from ./.mcp.json (never prints the key).
// Requires Node 18+.

import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync, chmodSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

if (typeof fetch !== 'function') { console.error('Node 18+ is required (global fetch). Current: ' + process.version); process.exit(1); }
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DATA = path.join(ROOT, 'hiveku-data');
let manifest;
try {
  manifest = JSON.parse(readFileSync(path.join(DATA, 'manifest.json'), 'utf8'));
} catch (e) {
  console.error('hiveku-data/manifest.json is missing or unreadable (' + e.message + ').');
  console.error('Regenerate it: run any download from the Hiveku sidebar (e.g. Hiveku: Download Department Data).');
  process.exit(1);
}
let mcp;
try {
  mcp = JSON.parse(readFileSync(path.join(ROOT, '.mcp.json'), 'utf8')).mcpServers.hiveku;
} catch (e) {
  console.error('Cannot read .mcp.json (need mcpServers.hiveku with url + Authorization header):', e.message);
  process.exit(1);
}
const ENDPOINT = mcp.url;
const AUTH = (mcp.headers || {}).Authorization || '';
if (!ENDPOINT || !AUTH) { console.error('.mcp.json hiveku entry is missing url or Authorization header.'); process.exit(1); }

// ── Minimal MCP client (JSON-RPC over streamable HTTP) ──────────────────────
// Ported from the extension's src/mcpClient.ts — keep the two in step. This
// script is the documented way to refresh hiveku-data WITHOUT the extension, so
// a fix that lands only in the extension never reaches an unattended pull.
//
// ONE budget for every call, set just past the edge timeout, replaces the old
// fixed 90s. The edge in front of Hiveku closes an idle connection at
// ~120-125s, and plenty of real tools are budgeted well past 90s server-side.
// Giving up before the server does not stop the work; it only reports a failure
// for a call that then succeeds.
const REQUEST_TIMEOUT_MS = 135000;
const REQUEST_TIMEOUT_S = Math.round(REQUEST_TIMEOUT_MS / 1000);
// The server's limiter is a FIXED 60s window and its 429 advertises the true
// remaining time, so a retry may legitimately have to wait a whole minute.
// Waking early just spends the one retry on a second 429.
const RATE_LIMIT_MAX_RETRY_SECONDS = 60;

let rpcId = 1, sessionId = null, initialized = false;

function clampRetrySeconds(n) {
  if (!Number.isFinite(n)) return 15;
  return Math.min(Math.max(Math.ceil(n), 1), RATE_LIMIT_MAX_RETRY_SECONDS);
}
// Fallback only — used when a 429 arrives without a Retry-After header.
function retryAfterFromProse(message) {
  if (!/rate limit/i.test(message)) return null;
  const m = String(message).match(/retry[_ ]after[_ :]*(\\d+)/i);
  return clampRetrySeconds(m ? Number(m[1]) : 15);
}

async function rpcOnce(method, params) {
  const headers = { Authorization: AUTH, 'Content-Type': 'application/json', Accept: 'application/json', 'User-Agent': '${hivekuUserAgent('HivekuDataRunner')}' };
  if (sessionId) headers['Mcp-Session-Id'] = sessionId;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), REQUEST_TIMEOUT_MS);
  let res;
  try {
    res = await fetch(ENDPOINT, { method: 'POST', headers, body: JSON.stringify({ jsonrpc: '2.0', id: rpcId++, method, params }), signal: ctrl.signal });
  } catch (err) {
    clearTimeout(timer);
    if (ctrl.signal.aborted) throw new Error('MCP request timed out after ' + REQUEST_TIMEOUT_S + 's (' + method + ')');
    throw err;
  }
  // The timer stays armed until the BODY is read. fetch resolves on headers, so
  // disarming it here left a server that answers 200 and then stalls mid-body
  // with no deadline at all — exactly the case the budget exists for.
  const sh = res.headers.get('mcp-session-id');
  if (sh) sessionId = sh;
  if (!res.ok) {
    let text = '';
    try { text = await res.text(); } catch { text = ''; } finally { clearTimeout(timer); }
    const detail = 'MCP HTTP ' + res.status + ': ' + text.slice(0, 300);
    if (res.status === 429) {
      // Retry-After is the limiter's own remaining-window figure. Take it over
      // the prose, which is the same number rendered into a sentence.
      const header = Number(res.headers.get('retry-after'));
      const limited = new Error(detail);
      limited.retryAfterSeconds = header > 0 ? clampRetrySeconds(header) : (retryAfterFromProse(text) || 15);
      throw limited;
    }
    throw new Error(detail);
  }
  if (res.status === 204) { clearTimeout(timer); return null; }
  let body;
  try {
    body = await res.json();
  } catch (err) {
    if (ctrl.signal.aborted) throw new Error('MCP response stalled after ' + REQUEST_TIMEOUT_S + 's while reading the body (' + method + ')');
    throw err;
  } finally { clearTimeout(timer); }
  if (body.error) throw new Error('MCP error ' + body.error.code + ': ' + body.error.message);
  return body.result;
}

// One polite retry after the delay the SERVER asked for. Datasets fan out five
// calls wide, so tripping the limiter on a big pull is normal; failing the
// whole department over it is not.
async function rpc(method, params) {
  try {
    return await rpcOnce(method, params);
  } catch (err) {
    const wait = (err && err.retryAfterSeconds) || retryAfterFromProse(err && err.message ? err.message : String(err));
    if (!wait) throw err;
    console.log('  rate limited by the server — waiting ' + wait + 's, then retrying once (' + method + ')');
    await new Promise((r) => setTimeout(r, wait * 1000));
    return await rpcOnce(method, params);
  }
}
async function callTool(name, args) {
  if (!initialized) {
    await rpc('initialize', { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 'hiveku-pull-data', version: '${RUNNER_VERSION}' } });
    await rpc('notifications/initialized', {}).catch(() => undefined);
    initialized = true;
  }
  const result = await rpc('tools/call', { name, arguments: args || {} });
  if (result && result.isError) throw new Error('Tool ' + name + ' errored: ' + (((result.content || [])[0] || {}).text || 'unknown'));
  const text = (((result || {}).content || [])[0] || {}).text;
  if (typeof text !== 'string') throw new Error('Tool ' + name + ' returned no text content');
  return JSON.parse(text);
}

// ── Ports of the extension's extraction/fan-out (keep in sync with deptData.ts) ──
function firstObjectArray(obj) {
  let fallback;
  for (const v of Object.values(obj)) {
    if (Array.isArray(v)) {
      if (v.length && typeof v[0] === 'object' && v[0] !== null) return v;
      if (!fallback) fallback = v;
    }
  }
  return fallback;
}
function extractRows(payload) {
  const inner = payload && typeof payload === 'object' && 'data' in payload ? payload.data : payload;
  if (Array.isArray(inner)) return inner;
  if (inner && typeof inner === 'object') { const a = firstObjectArray(inner); if (a) return a; }
  if (payload && typeof payload === 'object' && !Array.isArray(payload)) { const a = firstObjectArray(payload); if (a) return a; }
  return [];
}
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) { const i = next++; if (i >= items.length) return; out[i] = await fn(items[i], i); }
  });
  await Promise.all(workers);
  return out;
}
function daysAgoIso(n) { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().slice(0, 10); }
function resolveDyn(dyn) { const out = {}; for (const k of Object.keys(dyn || {})) out[k] = daysAgoIso(dyn[k]); return out; }
function slugify(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'item'; }
var MAX_EXTRA_PAGES = 40;
function paginationOf(raw) {
  if (raw && typeof raw === 'object') {
    var p = raw.pagination || (raw.data && raw.data.pagination);
    if (p && typeof p === 'object') return p;
  }
  return undefined;
}
// Follow a list tool's pagination envelope to completion (most routes cap limit
// ~100 and return { page, total_pages, total }). Stops if a tool ignores the
// page arg. Returns { rows, total, truncated } so a page-cap hit is recorded.
async function fetchPaged(tool, args) {
  var first = await callTool(tool, args);
  var rows = extractRows(first);
  var pg = paginationOf(first);
  var total = pg && pg.total != null ? Number(pg.total) : undefined;
  var totalPages = pg ? Number(pg.total_pages) || 1 : 1;
  var startPage = pg ? Number(pg.page) || 1 : 1;
  if (totalPages <= 1 || startPage >= totalPages) return { rows: rows, total: total };
  var last = Math.min(totalPages, startPage + MAX_EXTRA_PAGES);
  for (var p = startPage + 1; p <= last; p++) {
    var raw;
    try { raw = await callTool(tool, Object.assign({}, args, { page: p })); } catch { break; }
    var rpg = paginationOf(raw);
    if (!rpg || Number(rpg.page) !== p) break;
    rows = rows.concat(extractRows(raw));
  }
  var truncated = last < totalPages || (total != null && rows.length < total);
  return { rows: rows, total: total, truncated: truncated };
}

async function fetchDataset(ds) {
  try {
    const baseArgs = Object.assign({}, ds.args || {}, resolveDyn(ds.dyn_args));
    if (!ds.scope) { const r = await fetchPaged(ds.tool, baseArgs); return { rows: r.rows, total: r.total, truncated: r.truncated }; }
    let contexts = [{ args: {}, label: '' }];
    let firstStep = true;
    for (const step of ds.scope) {
      const isFirst = firstStep;
      firstStep = false;
      const expanded = await mapLimit(contexts, 5, async (ctx) => {
        let parents;
        // The ROOT parent listing failing means the dataset failed (dead key,
        // dead endpoint) — do not mistake that for "no parents = 0 rows".
        try { parents = extractRows(await callTool(step.parentTool, Object.assign({}, step.parentArgs || {}, ctx.args))); }
        catch (err) { if (isFirst) throw err; return []; }
        const out = [];
        for (const p of parents) {
          const pid = typeof p === 'string' ? p : p[step.parentIdKey];
          if (pid == null || pid === '') continue;
          const plabel = typeof p === 'string' ? p : (step.parentLabelKey ? (p[step.parentLabelKey] != null ? p[step.parentLabelKey] : pid) : pid);
          out.push({ args: Object.assign({}, ctx.args, { [step.argKey]: pid }), label: ctx.label ? ctx.label + ' / ' + plabel : String(plabel) });
        }
        return out;
      });
      contexts = expanded.flat();
      if (contexts.length === 0) break;
    }
    let anyTruncated = false;
    const chunks = await mapLimit(contexts, 5, async (ctx) => {
      try {
        const r = await fetchPaged(ds.tool, Object.assign({}, baseArgs, ctx.args));
        if (r.truncated) anyTruncated = true;
        return r.rows.map((row) => typeof row === 'string' ? { _parent: ctx.label, value: row } : Object.assign({ _parent: ctx.label }, row));
      } catch { return []; }
    });
    return { rows: chunks.flat(), parents: contexts.length, truncated: anyTruncated || undefined };
  } catch (err) {
    return { rows: [], error: err && err.message ? err.message : String(err) };
  }
}

function writeJson(file, value) {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(value, null, 2) + String.fromCharCode(10), 'utf8');
}

// Markdown docs. BT = backtick — kept out of this script's source on purpose
// (the extension generates this file from a template literal).
var BT = String.fromCharCode(96);
var NL = String.fromCharCode(10);
function code(s) { return BT + s + BT; }

// README per department, composed from ON-DISK dataset files (so a partial
// --dataset refresh still reports every dataset's true count + fetch time).
function writeDeptDocs(dept) {
  var dir = path.join(DATA, dept.id);
  if (dept.setup) writeFileSync(path.join(dir, 'SETUP.md'), dept.setup, 'utf8');
  var lines = [];
  for (const ds of dept.datasets) {
    var f = path.join(dir, ds.id + '.json');
    var st = null;
    try { st = JSON.parse(readFileSync(f, 'utf8')); } catch { continue; }
    var status = st.error
      ? 'error: ' + st.error
      : st.truncated
        ? 'TRUNCATED — ' + st.count + ' of ' + (st.total != null ? st.total : '?') + ' rows (page cap hit; re-pull via the live tool for the full set)'
        : st.count + ' rows (fetched ' + st.fetched_at + ')';
    lines.push('- ' + code(ds.id + '.json') + ' - ' + ds.label + ' (' + status + '). Tool: ' + code(ds.tool) + '.');
  }
  for (const ref of dept.references || []) {
    if (existsSync(path.join(dir, ref.id + '.json'))) {
      lines.push('- ' + code(ref.id + '.json') + ' - ' + ref.label + ' (reference). Tool: ' + code(ref.tool) + '.');
    }
  }
  var crud = dept.crud
    ? NL + '## CRUD - how to change this data' + NL + dept.crud + NL
    : dept.read_only
      ? NL + '## Read-only' + NL + 'This department has no MCP write tools - analyze locally; changes happen in the Hiveku dashboard.' + NL
      : NL + 'To act on this data (not just read it), call the live MCP tools (named per dataset above).' + NL;
  var setup = dept.setup ? NL + '## Setup / connect' + NL + 'See ' + code('SETUP.md') + ' in this folder for the exact steps to connect the integration(s).' + NL : '';
  var md = '# ' + dept.label + ' - local data' + NL + NL
    + 'Snapshot pulled from Hiveku. List files are { dataset, count, fetched_at, rows: [...] } - check' + NL
    + 'fetched_at before trusting. Refresh: ' + code('node .hiveku/pull-data.mjs ' + dept.id) + ' (or --stale / --dataset).' + NL
    + 'Scoped datasets tag each row with ' + code('_parent') + ' (the project/connection it came from).' + NL + NL
    + '## Datasets' + NL + lines.join(NL) + NL + crud + setup;
  writeFileSync(path.join(dir, 'README.md'), md, 'utf8');
}

// ── Account memory (read-only copy) ─────────────────────────────────────────
// The account memory is the one document of business facts every department
// agent reads. It is NOT a department: owners and admins edit it on the Hiveku
// dashboard, nothing uploads this copy, and every run except --dataset (a
// targeted refresh after a write) refreshes hiveku-data/account/ACCOUNT_MEMORY.md.
// The renderer is a port of the extension's src/accountMemory.ts, which writes
// the same bytes as the Claude Code plugin and hiveku-sync: one file, whichever
// tool refreshed it last. Keep them in step (the extension's tests compare bytes).
var ACCOUNT_TARGET = 'account';
var ACCOUNT_MEMORY_TOOL = 'account_memory_get';
var ACCOUNT_MEMORY_REL = 'hiveku-data/account/ACCOUNT_MEMORY.md';
var ACCOUNT_MEMORY_PATH = path.join(DATA, 'account', 'ACCOUNT_MEMORY.md');
var APP_URL = 'https://app.hiveku.com';
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// A changed shape is an ERROR, never an empty memory written over a real one.
function normalizeAccountMemory(payload) {
  var inner = payload && typeof payload === 'object' && !Array.isArray(payload) && 'data' in payload ? payload.data : payload;
  if (!inner || typeof inner !== 'object' || Array.isArray(inner)) {
    throw new Error(ACCOUNT_MEMORY_TOOL + ' returned an unexpected shape (no object)');
  }
  if (typeof inner.content !== 'string' || !Number.isFinite(Number(inner.version))) {
    throw new Error(ACCOUNT_MEMORY_TOOL + ' returned an unexpected shape (no content or version)');
  }
  var raw = Array.isArray(inner.suggestions) ? inner.suggestions : [];
  return {
    content: inner.content,
    version: Number(inner.version),
    updated_at: typeof inner.updated_at === 'string' ? inner.updated_at : null,
    suggestions: raw
      .filter(function (s) { return s && typeof s === 'object' && typeof s.text === 'string' && s.text.trim(); })
      .map(function (s) {
        return {
          id: typeof s.id === 'string' ? s.id : '',
          at: typeof s.at === 'string' ? s.at : '',
          source: typeof s.source === 'string' && s.source.trim() ? s.source : 'Unknown',
          text: s.text,
        };
      }),
    suggestions_version: Number.isFinite(Number(inner.suggestions_version)) ? Number(inner.suggestions_version) : 0,
    truncated: inner.truncated === true,
  };
}
function amWhen(value) {
  if (!value) return 'unknown time';
  var d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toISOString().slice(0, 16).replace('T', ' ') + ' UTC';
}
function amOneLine(value) { return String(value).replace(/[\\r\\n\\u2028\\u2029]+/g, ' ').trim(); }
function amYaml(value) { return '"' + String(value).replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"') + '"'; }
// Account-scoped when the id is a real UUID; the unscoped page otherwise, never a half-built URL.
function accountMemoryDashboardUrl(accountId) {
  return typeof accountId === 'string' && UUID_RE.test(accountId)
    ? APP_URL + '/' + accountId.toLowerCase() + '/dashboard/memory'
    : APP_URL + '/dashboard/memory';
}
function renderAccountMemory(memory, accountId, fetchedAt) {
  var editUrl = accountMemoryDashboardUrl(accountId);
  var fm = ['---', 'read_only: true', 'source_tool: ' + ACCOUNT_MEMORY_TOOL, 'version: ' + memory.version]
    .concat(memory.updated_at ? ['updated_at: ' + amYaml(memory.updated_at)] : [])
    .concat([
      'suggestions: ' + memory.suggestions.length,
      'suggestions_version: ' + memory.suggestions_version,
      'fetched_at: ' + amYaml(fetchedAt),
      'edit_url: ' + amYaml(editUrl),
      '---',
      '',
    ]);
  var lines = [
    '# Account memory',
    '',
    '> This is a read-only copy of the account memory, the facts about the business that every',
    '> Hiveku department agent reads. Owners and admins edit it on the Hiveku dashboard:',
    '> ' + editUrl,
    '>',
    '> Changes made to this file are not saved to Hiveku. The next pull replaces this file, and',
    '> nothing uploads it. To add a fact, suggest it with account_memory_append (an owner or admin',
    '> reviews it on the dashboard), or ask an owner or admin to change the document there.',
    '> It is internal to the team: do not quote it to customers.',
    '',
  ];
  if (memory.version > 0 && memory.content.trim()) {
    lines.push('Version ' + memory.version + ', last changed ' + amWhen(memory.updated_at) + '.');
    if (memory.truncated) {
      lines.push('Agents see a shortened version: with the suggestions, it is longer than the 8,000 characters they read.');
    }
    lines.push('', '---', '', memory.content.replace(/\\s+$/, ''), '', '---', '');
  } else {
    lines.push('Nothing has been written yet. An owner or admin can start it on the dashboard.', '');
  }
  lines.push('# Suggestions from agents, not reviewed yet', '');
  if (memory.suggestions.length) {
    lines.push('These lines are not part of the account memory until an owner or admin keeps them on the dashboard.', '');
    for (const s of memory.suggestions) {
      lines.push('- ' + amOneLine(s.text) + ' (suggested by ' + amOneLine(s.source) + ', ' + amWhen(s.at) + ')');
    }
  } else {
    lines.push('None waiting.');
  }
  lines.push('');
  return fm.join(NL) + lines.join(NL);
}
// Replace the copy even when a previous run left it read-only: write a temp
// beside it and rename over it (a rename needs the FOLDER writable). Windows
// refuses a rename onto a read-only file, so on that refusal open it and retry.
function writeReadOnlyFile(file, text) {
  mkdirSync(path.dirname(file), { recursive: true });
  var tmp = path.join(path.dirname(file), '.' + path.basename(file) + '.' + process.pid + '.tmp');
  writeFileSync(tmp, text, 'utf8');
  try {
    renameSync(tmp, file);
  } catch (err) {
    if (!err || (err.code !== 'EPERM' && err.code !== 'EACCES')) { try { unlinkSync(tmp); } catch { /* gone */ } throw err; }
    chmodSync(file, 0o644);
    renameSync(tmp, file);
  }
  chmodSync(file, 0o444);
}
// The key is pinned to one account, so get_account_info's first row is it. Any
// failure (a narrowed profile, an older server) gives the unscoped dashboard link.
async function resolveAccountId() {
  try {
    var r = await callTool('get_account_info', {});
    var data = r && typeof r === 'object' && 'data' in r ? r.data : r;
    var row = Array.isArray(data) ? data[0] : data;
    var id = row && typeof row.id === 'string' ? row.id.trim() : '';
    return UUID_RE.test(id) ? id : null;
  } catch { return null; }
}
// Never throws. A failed read keeps the previous copy (kept says whether there was one).
async function syncAccountMemory() {
  var fetchedAt = new Date().toISOString();
  var memory;
  try {
    memory = normalizeAccountMemory(await callTool(ACCOUNT_MEMORY_TOOL, {}));
  } catch (err) {
    var error = String(err && err.message ? err.message : err);
    var kept = existsSync(ACCOUNT_MEMORY_PATH);
    console.log('  account/ACCOUNT_MEMORY.md: ERROR ' + error.slice(0, 120) + (kept ? ' (kept previous copy)' : ''));
    return { ok: false, error: error, kept: kept, fetched_at: fetchedAt };
  }
  try {
    writeReadOnlyFile(ACCOUNT_MEMORY_PATH, renderAccountMemory(memory, await resolveAccountId(), fetchedAt));
  } catch (err) {
    var werr = String(err && err.message ? err.message : err);
    console.log('  account/ACCOUNT_MEMORY.md: ERROR ' + werr.slice(0, 120));
    return { ok: false, error: werr, kept: existsSync(ACCOUNT_MEMORY_PATH), fetched_at: fetchedAt };
  }
  var n = memory.suggestions.length;
  console.log('  account/ACCOUNT_MEMORY.md: ' + (memory.version > 0 ? 'version ' + memory.version : 'empty') + ', '
    + n + ' suggestion' + (n === 1 ? '' : 's') + ' (read-only; edit on the dashboard)');
  return { ok: true, version: memory.version, suggestions: n, fetched_at: fetchedAt };
}
// fetched_at from the copy's front matter, or null when there is no copy.
function accountMemoryFreshness() {
  try {
    var m = /^fetched_at:\\s*"([^"]+)"\\s*$/m.exec(readFileSync(ACCOUNT_MEMORY_PATH, 'utf8'));
    return m ? m[1] : null;
  } catch { return null; }
}

// ── Pull one department (same file shapes as the extension's export) ────────
async function pullDept(dept, onlyDataset) {
  const dir = path.join(DATA, dept.id);
  const fetchedAt = new Date().toISOString();
  const status = { fetched_at: fetchedAt, datasets: {} };
  for (const ds of dept.datasets) {
    if (onlyDataset && ds.id !== onlyDataset) continue;
    const r = await fetchDataset(ds);
    const scopedBy = ds.scope ? ds.scope.map((s) => s.parentTool).join(' -> ') : null;
    const file = path.join(dir, ds.id + '.json');
    if (r.error && existsSync(file)) {
      // A failed refresh must never clobber a good snapshot — keep the old file.
      console.log('  ' + dept.id + '/' + ds.id + ': ERROR ' + r.error.slice(0, 120) + ' (kept previous snapshot)');
    } else {
      writeJson(file, Object.assign(
        { dataset: ds.id, label: ds.label, tool: ds.tool, scoped_by: scopedBy, parents: r.parents != null ? r.parents : null, count: r.rows.length },
        r.total != null ? { total: r.total } : {},
        r.truncated ? { truncated: true } : {},
        { fetched_at: fetchedAt },
        r.error ? { error: r.error } : {},
        { rows: r.rows },
      ));
      var msg = r.error ? 'ERROR ' + r.error.slice(0, 120) : r.rows.length + ' rows';
      if (r.truncated) msg += ' — TRUNCATED at ' + r.rows.length + (r.total != null ? ' of ' + r.total : '') + ' (page cap ' + MAX_EXTRA_PAGES + '; re-pull this dataset via the live tool for the full set)';
      console.log('  ' + dept.id + '/' + ds.id + ': ' + msg);
    }
    status.datasets[ds.id] = { count: r.rows.length, error: r.error || null, truncated: r.truncated || false };
    if (ds.detail && r.rows.length && !r.error) {
      const det = ds.detail;
      const subdir = path.join(dir, det.dir || ds.id);
      const written = await mapLimit(r.rows, 5, async (row) => {
        const id = row[det.idKey || 'id'];
        if (id == null) return false;
        try {
          const data = await callTool(det.detailTool, { [det.argKey || 'id']: id });
          const inner = data && typeof data === 'object' && 'data' in data ? data.data : data;
          const name = String(row[det.nameKey || 'name'] != null ? row[det.nameKey || 'name'] : id);
          writeJson(path.join(subdir, slugify(name) + '-' + String(id).slice(0, 8) + '.json'), inner);
          return true;
        } catch { return false; }
      });
      console.log('  ' + dept.id + '/' + (det.dir || ds.id) + '/: ' + written.filter(Boolean).length + ' detail files');
    }
  }
  if (!onlyDataset) {
    for (const ref of dept.references || []) {
      try {
        const data = await callTool(ref.tool, ref.args || {});
        const inner = data && typeof data === 'object' && 'data' in data ? data.data : data;
        writeJson(path.join(dir, ref.id + '.json'), inner != null ? inner : {});
        console.log('  ' + dept.id + '/' + ref.id + ': reference ok');
      } catch (err) {
        console.log('  ' + dept.id + '/' + ref.id + ': ERROR ' + String(err && err.message ? err.message : err).slice(0, 120));
      }
    }
  }
  try { writeDeptDocs(dept); } catch { /* docs are best-effort */ }
  return status;
}

function deptFreshness(deptId) {
  const dir = path.join(DATA, deptId);
  if (!existsSync(dir)) return null;
  let newest = null;
  const dept = manifest.departments.find((d) => d.id === deptId);
  for (const ds of (dept && dept.datasets) || []) {
    const f = path.join(dir, ds.id + '.json');
    if (!existsSync(f)) continue;
    try {
      const at = JSON.parse(readFileSync(f, 'utf8')).fetched_at;
      if (at && (!newest || at > newest)) newest = at;
    } catch { /* unreadable snapshot = treat as missing */ }
  }
  return newest;
}

// ── CLI ──────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const byId = new Map(manifest.departments.map((d) => [d.id, d]));
function usage() {
  console.log('Departments (* = your defaults): ' + manifest.departments.map((d) => (manifest.default_departments.includes(d.id) ? d.id + '*' : d.id)).join(' '));
  console.log('Usage: node .hiveku/pull-data.mjs <dept ...> | account | --default | --all | --stale [hours] | --dataset <dept:id> | --list');
  console.log('Every run except --dataset also refreshes ' + ACCOUNT_MEMORY_REL + ' (read-only; owners edit it on the dashboard).');
}
async function main() {
  let targets = [];
  let onlyDataset = null;
  // The account memory rides along with every run (one small read), never with
  // --dataset, which is a targeted refresh after a write.
  let withAccountMemory = true;
  if (argv.includes('--list') || argv.length === 0) {
    for (const d of manifest.departments) {
      const fresh = deptFreshness(d.id);
      const mark = manifest.default_departments.includes(d.id) ? '*' : ' ';
      console.log(mark + ' ' + d.id.padEnd(12) + (fresh ? 'fetched ' + fresh : 'not downloaded'));
    }
    const accountFresh = accountMemoryFreshness();
    console.log('  ' + ACCOUNT_TARGET.padEnd(12) + (accountFresh ? 'fetched ' + accountFresh : 'not downloaded') + ' (account memory, read-only)');
    if (argv.length === 0) usage();
    return;
  }
  if (argv[0] === '--dataset') {
    const parts = String(argv[1] || '').split(':');
    const dept = byId.get(parts[0]);
    if (!dept || !parts[1]) { console.error('Expected --dataset <dept>:<dataset-id>'); usage(); process.exit(1); }
    if (!dept.datasets.some((ds) => ds.id === parts[1])) {
      console.error('Unknown dataset "' + parts[1] + '" for ' + dept.id + '. Valid: ' + dept.datasets.map((ds) => ds.id).join(', '));
      process.exit(1);
    }
    targets = [dept]; onlyDataset = parts[1]; withAccountMemory = false;
  } else if (argv.includes('--all')) {
    targets = manifest.departments;
  } else if (argv.includes('--default')) {
    targets = manifest.default_departments.map((id) => byId.get(id)).filter(Boolean);
  } else if (argv.includes('--stale')) {
    const idx = argv.indexOf('--stale');
    const hours = Number(argv[idx + 1]) > 0 ? Number(argv[idx + 1]) : 12;
    const cutoff = new Date(Date.now() - hours * 3600000).toISOString();
    targets = manifest.default_departments.map((id) => byId.get(id)).filter(Boolean)
      .filter((d) => { const f = deptFreshness(d.id); return !f || f < cutoff; });
    const accountFresh = accountMemoryFreshness();
    withAccountMemory = !accountFresh || accountFresh < cutoff;
    if (!targets.length && !withAccountMemory) { console.log('All default departments fresh (within ' + hours + 'h).'); return; }
  } else {
    const named = argv.filter((a) => a !== ACCOUNT_TARGET);
    const unknown = named.filter((a) => !byId.has(a));
    if (unknown.length) { console.error('Unknown department(s): ' + unknown.join(', ')); usage(); process.exit(1); }
    targets = named.map((a) => byId.get(a));
  }
  let statusAll = {};
  const statusFile = path.join(DATA, 'STATUS.json');
  try { statusAll = JSON.parse(readFileSync(statusFile, 'utf8')); } catch { statusAll = {}; }
  if (!statusAll || typeof statusAll !== 'object' || Array.isArray(statusAll)) statusAll = {};
  // The extension's exporter records failures in a top-level \`failed\` array
  // and writes \`departments\` as an ARRAY of ids. Keep the failures of every
  // department this run does not touch, and normalize \`departments\` to the
  // object this runner keys by id (a named key on an array vanishes in JSON).
  const targetIds = new Set(targets.map((d) => d.id));
  const priorFailed = Array.isArray(statusAll.failed)
    ? statusAll.failed.filter((f) => f && typeof f.department === 'string' && !targetIds.has(f.department))
    : [];
  if (!statusAll.departments || typeof statusAll.departments !== 'object' || Array.isArray(statusAll.departments)) statusAll.departments = {};
  let accountMemory = null;
  if (withAccountMemory) {
    console.log('Account memory (' + ACCOUNT_TARGET + ')');
    accountMemory = await syncAccountMemory();
  }
  let okDepts = 0;
  for (const dept of targets) {
    console.log(dept.label + ' (' + dept.id + ')');
    const st = await pullDept(dept, onlyDataset);
    const prev = statusAll.departments[dept.id];
    // A single-dataset refresh merges into the department entry, never replaces it.
    statusAll.departments[dept.id] = onlyDataset && prev && prev.datasets
      ? { fetched_at: st.fetched_at, datasets: Object.assign({}, prev.datasets, st.datasets) }
      : st;
    const errs = Object.values(st.datasets).filter((x) => x.error).length;
    const total = Object.keys(st.datasets).length;
    // total === 0 = references-only department — references log their own errors.
    if (total === 0 || total > errs) okDepts++;
  }
  const nowIso = new Date().toISOString();
  statusAll.updated_at = nowIso;
  // Mirror the extension exporter's fields so an agent can read ONE marker
  // regardless of which writer refreshed last. \`failed\` is the important one:
  // an empty dataset file means "not retrieved" here, not "no data".
  statusAll.fetched_at = nowIso;
  const freshFailed = Object.entries(statusAll.departments).flatMap(([k, v]) =>
    Object.entries((v && v.datasets) || {})
      .filter(([, d]) => d && d.error)
      .map(([ds, d]) => ({ department: k, dataset: ds, error: String(d.error).slice(0, 200) })),
  );
  // The account memory is not a department, so it has its own entry (the
  // plugin's shape). A run that read it replaces that entry; a run that did not keeps it.
  let accountFailed = priorFailed.filter((f) => f.department === ACCOUNT_TARGET);
  // Departments with a block are recomputed above; keep the rest as they were.
  const otherPriorFailed = priorFailed.filter((f) => f.department !== ACCOUNT_TARGET && !(f.department in statusAll.departments));
  if (accountMemory) {
    statusAll.account_memory = Object.assign(
      { file: ACCOUNT_MEMORY_REL, read_only: true, fetched_at: accountMemory.fetched_at },
      accountMemory.ok
        ? { version: accountMemory.version, suggestions: accountMemory.suggestions }
        : { error: accountMemory.error.slice(0, 200), kept_previous: accountMemory.kept },
    );
    accountFailed = accountMemory.ok
      ? []
      : [{ department: ACCOUNT_TARGET, dataset: 'account-memory', error: accountMemory.error.slice(0, 200) }];
  }
  statusAll.failed = otherPriorFailed.concat(accountFailed, freshFailed);
  statusAll.runner_version = ${RUNNER_VERSION};
  writeJson(statusFile, statusAll);
  if (targets.length && okDepts === 0) { console.error('Every dataset failed — check the account key in .mcp.json.'); process.exit(1); }
  // Only the account memory was asked for: its one read is the whole run.
  if (!targets.length && accountMemory && !accountMemory.ok) { console.error('The account memory could not be read; the previous copy (if any) was kept.'); process.exit(1); }
  console.log('Done. Data in hiveku-data/ — work from these local files; use live MCP tools for writes.');
}
main().catch((err) => { console.error(err && err.message ? err.message : err); process.exit(1); });
`;
}
