/**
 * Local data runner — lets Claude Code pull/refresh `hiveku-data/` ITSELF,
 * without the extension in the loop and without routing row data through the
 * model: a generated `.hiveku/pull-data.mjs` executes `hiveku-data/manifest.json`
 * (serialized from the deptData registry) against the account's MCP endpoint.
 *
 * Division of labor (the anti-drift contract):
 *   - manifest.json  = WHAT to pull (tools, args, windows, scope chains) —
 *     regenerated from deptData.DEPARTMENTS on every scaffold/export.
 *   - pull-data.mjs  = HOW to pull (MCP protocol, fan-out, file shapes) —
 *     generic and dataset-agnostic; overwritten on every regeneration
 *     (version-stamped, never hand-edited).
 *
 * Output shapes are byte-compatible with dataExport.ts so the extension and the
 * runner can refresh the same files interchangeably.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { dataManifest } from './deptData';

export const RUNNER_VERSION = 2;
export const RUNNER_REL_PATH = path.join('.hiveku', 'pull-data.mjs');

/**
 * Write (or refresh) the runner + manifest into an account folder.
 * When `defaultDeptIds` is omitted (e.g. a partial department download), the
 * EXISTING manifest's default_departments are preserved — a one-department
 * export must not narrow what --default/--stale pull. Only the scaffold (which
 * knows the role) passes explicit defaults.
 */
export async function writeDataRunner(baseDir: string, defaultDeptIds?: string[]): Promise<void> {
  const manifestFile = path.join(baseDir, 'hiveku-data', 'manifest.json');
  let defaults = defaultDeptIds;
  if (!defaults) {
    try {
      const prev = JSON.parse(await fs.readFile(manifestFile, 'utf8')) as { default_departments?: string[] };
      if (Array.isArray(prev.default_departments) && prev.default_departments.length) defaults = prev.default_departments;
    } catch {
      /* no prior manifest — dataManifest falls back to all departments */
    }
  }
  const manifest = dataManifest(defaults);
  await fs.mkdir(path.join(baseDir, 'hiveku-data'), { recursive: true });
  await fs.writeFile(manifestFile, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  await fs.mkdir(path.join(baseDir, '.hiveku'), { recursive: true });
  await fs.writeFile(path.join(baseDir, RUNNER_REL_PATH), runnerScript(), 'utf8');
}

/**
 * The generated script. Codegen discipline: every backslash that must reach the
 * file is written `\\`; the script itself avoids backtick templates so it can
 * never be confused with this template's own syntax.
 */
function runnerScript(): string {
  return `#!/usr/bin/env node
// Hiveku data runner v${RUNNER_VERSION} — GENERATED by the Hiveku VS Code extension. Do not edit
// (regenerated on every scaffold/export). Pulls account department data into
// hiveku-data/<dept>/ so Claude Code can work on LOCAL files instead of live calls.
//
// Usage (run from anywhere inside the account folder):
//   node .hiveku/pull-data.mjs seo ppc          pull specific departments
//   node .hiveku/pull-data.mjs --default        pull your role's departments
//   node .hiveku/pull-data.mjs --all            pull every department
//   node .hiveku/pull-data.mjs --stale 12       pull default departments older than N hours (default 12)
//   node .hiveku/pull-data.mjs --dataset ppc:campaigns   refresh ONE dataset (e.g. after a write)
//   node .hiveku/pull-data.mjs --list           departments + local freshness
//
// Reads the account MCP endpoint + key from ./.mcp.json (never prints the key).
// Requires Node 18+.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

if (typeof fetch !== 'function') { console.error('Node 18+ is required (global fetch). Current: ' + process.version); process.exit(1); }
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DATA = path.join(ROOT, 'hiveku-data');
let manifest;
try {
  manifest = JSON.parse(readFileSync(path.join(DATA, 'manifest.json'), 'utf8'));
} catch (e) {
  console.error('hiveku-data/manifest.json is missing or unreadable (' + e.message + ').');
  console.error('Regenerate it: run any download from the Hiveku sidebar (e.g. Hiveku: Download Department Data).');
  process.exit(1);
}
let mcp;
try {
  mcp = JSON.parse(readFileSync(path.join(ROOT, '.mcp.json'), 'utf8')).mcpServers.hiveku;
} catch (e) {
  console.error('Cannot read .mcp.json (need mcpServers.hiveku with url + Authorization header):', e.message);
  process.exit(1);
}
const ENDPOINT = mcp.url;
const AUTH = (mcp.headers || {}).Authorization || '';
if (!ENDPOINT || !AUTH) { console.error('.mcp.json hiveku entry is missing url or Authorization header.'); process.exit(1); }

// ── Minimal MCP client (JSON-RPC over streamable HTTP) ──────────────────────
let rpcId = 1, sessionId = null, initialized = false;
async function rpc(method, params) {
  const headers = { Authorization: AUTH, 'Content-Type': 'application/json', Accept: 'application/json' };
  if (sessionId) headers['Mcp-Session-Id'] = sessionId;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 90000);
  let res;
  try {
    res = await fetch(ENDPOINT, { method: 'POST', headers, body: JSON.stringify({ jsonrpc: '2.0', id: rpcId++, method, params }), signal: ctrl.signal });
  } catch (err) {
    if (ctrl.signal.aborted) throw new Error('MCP request timed out after 90s (' + method + ')');
    throw err;
  } finally { clearTimeout(timer); }
  const sh = res.headers.get('mcp-session-id');
  if (sh) sessionId = sh;
  if (!res.ok) throw new Error('MCP HTTP ' + res.status + ': ' + (await res.text().catch(() => '')).slice(0, 300));
  if (res.status === 204) return null;
  const body = await res.json();
  if (body.error) throw new Error('MCP error ' + body.error.code + ': ' + body.error.message);
  return body.result;
}
async function callTool(name, args) {
  if (!initialized) {
    await rpc('initialize', { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 'hiveku-pull-data', version: '${RUNNER_VERSION}' } });
    await rpc('notifications/initialized', {}).catch(() => undefined);
    initialized = true;
  }
  const result = await rpc('tools/call', { name, arguments: args || {} });
  if (result && result.isError) throw new Error('Tool ' + name + ' errored: ' + (((result.content || [])[0] || {}).text || 'unknown'));
  const text = (((result || {}).content || [])[0] || {}).text;
  if (typeof text !== 'string') throw new Error('Tool ' + name + ' returned no text content');
  return JSON.parse(text);
}

// ── Ports of the extension's extraction/fan-out (keep in sync with deptData.ts) ──
function firstObjectArray(obj) {
  let fallback;
  for (const v of Object.values(obj)) {
    if (Array.isArray(v)) {
      if (v.length && typeof v[0] === 'object' && v[0] !== null) return v;
      if (!fallback) fallback = v;
    }
  }
  return fallback;
}
function extractRows(payload) {
  const inner = payload && typeof payload === 'object' && 'data' in payload ? payload.data : payload;
  if (Array.isArray(inner)) return inner;
  if (inner && typeof inner === 'object') { const a = firstObjectArray(inner); if (a) return a; }
  if (payload && typeof payload === 'object' && !Array.isArray(payload)) { const a = firstObjectArray(payload); if (a) return a; }
  return [];
}
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) { const i = next++; if (i >= items.length) return; out[i] = await fn(items[i], i); }
  });
  await Promise.all(workers);
  return out;
}
function daysAgoIso(n) { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().slice(0, 10); }
function resolveDyn(dyn) { const out = {}; for (const k of Object.keys(dyn || {})) out[k] = daysAgoIso(dyn[k]); return out; }
function slugify(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'item'; }
var MAX_EXTRA_PAGES = 40;
function paginationOf(raw) {
  if (raw && typeof raw === 'object') {
    var p = raw.pagination || (raw.data && raw.data.pagination);
    if (p && typeof p === 'object') return p;
  }
  return undefined;
}
// Follow a list tool's pagination envelope to completion (most routes cap limit
// ~100 and return { page, total_pages, total }). Stops if a tool ignores the
// page arg. Returns { rows, total, truncated } so a page-cap hit is recorded.
async function fetchPaged(tool, args) {
  var first = await callTool(tool, args);
  var rows = extractRows(first);
  var pg = paginationOf(first);
  var total = pg && pg.total != null ? Number(pg.total) : undefined;
  var totalPages = pg ? Number(pg.total_pages) || 1 : 1;
  var startPage = pg ? Number(pg.page) || 1 : 1;
  if (totalPages <= 1 || startPage >= totalPages) return { rows: rows, total: total };
  var last = Math.min(totalPages, startPage + MAX_EXTRA_PAGES);
  for (var p = startPage + 1; p <= last; p++) {
    var raw;
    try { raw = await callTool(tool, Object.assign({}, args, { page: p })); } catch { break; }
    var rpg = paginationOf(raw);
    if (!rpg || Number(rpg.page) !== p) break;
    rows = rows.concat(extractRows(raw));
  }
  var truncated = last < totalPages || (total != null && rows.length < total);
  return { rows: rows, total: total, truncated: truncated };
}

async function fetchDataset(ds) {
  try {
    const baseArgs = Object.assign({}, ds.args || {}, resolveDyn(ds.dyn_args));
    if (!ds.scope) { const r = await fetchPaged(ds.tool, baseArgs); return { rows: r.rows, total: r.total, truncated: r.truncated }; }
    let contexts = [{ args: {}, label: '' }];
    let firstStep = true;
    for (const step of ds.scope) {
      const isFirst = firstStep;
      firstStep = false;
      const expanded = await mapLimit(contexts, 5, async (ctx) => {
        let parents;
        // The ROOT parent listing failing means the dataset failed (dead key,
        // dead endpoint) — do not mistake that for "no parents = 0 rows".
        try { parents = extractRows(await callTool(step.parentTool, Object.assign({}, step.parentArgs || {}, ctx.args))); }
        catch (err) { if (isFirst) throw err; return []; }
        const out = [];
        for (const p of parents) {
          const pid = typeof p === 'string' ? p : p[step.parentIdKey];
          if (pid == null || pid === '') continue;
          const plabel = typeof p === 'string' ? p : (step.parentLabelKey ? (p[step.parentLabelKey] != null ? p[step.parentLabelKey] : pid) : pid);
          out.push({ args: Object.assign({}, ctx.args, { [step.argKey]: pid }), label: ctx.label ? ctx.label + ' / ' + plabel : String(plabel) });
        }
        return out;
      });
      contexts = expanded.flat();
      if (contexts.length === 0) break;
    }
    let anyTruncated = false;
    const chunks = await mapLimit(contexts, 5, async (ctx) => {
      try {
        const r = await fetchPaged(ds.tool, Object.assign({}, baseArgs, ctx.args));
        if (r.truncated) anyTruncated = true;
        return r.rows.map((row) => typeof row === 'string' ? { _parent: ctx.label, value: row } : Object.assign({ _parent: ctx.label }, row));
      } catch { return []; }
    });
    return { rows: chunks.flat(), parents: contexts.length, truncated: anyTruncated || undefined };
  } catch (err) {
    return { rows: [], error: err && err.message ? err.message : String(err) };
  }
}

function writeJson(file, value) {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(value, null, 2) + String.fromCharCode(10), 'utf8');
}

// Markdown docs. BT = backtick — kept out of this script's source on purpose
// (the extension generates this file from a template literal).
var BT = String.fromCharCode(96);
var NL = String.fromCharCode(10);
function code(s) { return BT + s + BT; }

// README per department, composed from ON-DISK dataset files (so a partial
// --dataset refresh still reports every dataset's true count + fetch time).
function writeDeptDocs(dept) {
  var dir = path.join(DATA, dept.id);
  if (dept.setup) writeFileSync(path.join(dir, 'SETUP.md'), dept.setup, 'utf8');
  var lines = [];
  for (const ds of dept.datasets) {
    var f = path.join(dir, ds.id + '.json');
    var st = null;
    try { st = JSON.parse(readFileSync(f, 'utf8')); } catch { continue; }
    var status = st.error
      ? 'error: ' + st.error
      : st.truncated
        ? 'TRUNCATED — ' + st.count + ' of ' + (st.total != null ? st.total : '?') + ' rows (page cap hit; re-pull via the live tool for the full set)'
        : st.count + ' rows (fetched ' + st.fetched_at + ')';
    lines.push('- ' + code(ds.id + '.json') + ' - ' + ds.label + ' (' + status + '). Tool: ' + code(ds.tool) + '.');
  }
  for (const ref of dept.references || []) {
    if (existsSync(path.join(dir, ref.id + '.json'))) {
      lines.push('- ' + code(ref.id + '.json') + ' - ' + ref.label + ' (reference). Tool: ' + code(ref.tool) + '.');
    }
  }
  var crud = dept.crud
    ? NL + '## CRUD - how to change this data' + NL + dept.crud + NL
    : dept.read_only
      ? NL + '## Read-only' + NL + 'This department has no MCP write tools - analyze locally; changes happen in the Hiveku dashboard.' + NL
      : NL + 'To act on this data (not just read it), call the live MCP tools (named per dataset above).' + NL;
  var setup = dept.setup ? NL + '## Setup / connect' + NL + 'See ' + code('SETUP.md') + ' in this folder for the exact steps to connect the integration(s).' + NL : '';
  var md = '# ' + dept.label + ' - local data' + NL + NL
    + 'Snapshot pulled from Hiveku. List files are { dataset, count, fetched_at, rows: [...] } - check' + NL
    + 'fetched_at before trusting. Refresh: ' + code('node .hiveku/pull-data.mjs ' + dept.id) + ' (or --stale / --dataset).' + NL
    + 'Scoped datasets tag each row with ' + code('_parent') + ' (the project/connection it came from).' + NL + NL
    + '## Datasets' + NL + lines.join(NL) + NL + crud + setup;
  writeFileSync(path.join(dir, 'README.md'), md, 'utf8');
}

// ── Pull one department (same file shapes as the extension's export) ────────
async function pullDept(dept, onlyDataset) {
  const dir = path.join(DATA, dept.id);
  const fetchedAt = new Date().toISOString();
  const status = { fetched_at: fetchedAt, datasets: {} };
  for (const ds of dept.datasets) {
    if (onlyDataset && ds.id !== onlyDataset) continue;
    const r = await fetchDataset(ds);
    const scopedBy = ds.scope ? ds.scope.map((s) => s.parentTool).join(' -> ') : null;
    const file = path.join(dir, ds.id + '.json');
    if (r.error && existsSync(file)) {
      // A failed refresh must never clobber a good snapshot — keep the old file.
      console.log('  ' + dept.id + '/' + ds.id + ': ERROR ' + r.error.slice(0, 120) + ' (kept previous snapshot)');
    } else {
      writeJson(file, Object.assign(
        { dataset: ds.id, label: ds.label, tool: ds.tool, scoped_by: scopedBy, parents: r.parents != null ? r.parents : null, count: r.rows.length },
        r.total != null ? { total: r.total } : {},
        r.truncated ? { truncated: true } : {},
        { fetched_at: fetchedAt },
        r.error ? { error: r.error } : {},
        { rows: r.rows },
      ));
      var msg = r.error ? 'ERROR ' + r.error.slice(0, 120) : r.rows.length + ' rows';
      if (r.truncated) msg += ' — TRUNCATED at ' + r.rows.length + (r.total != null ? ' of ' + r.total : '') + ' (page cap ' + MAX_EXTRA_PAGES + '; re-pull this dataset via the live tool for the full set)';
      console.log('  ' + dept.id + '/' + ds.id + ': ' + msg);
    }
    status.datasets[ds.id] = { count: r.rows.length, error: r.error || null, truncated: r.truncated || false };
    if (ds.detail && r.rows.length && !r.error) {
      const det = ds.detail;
      const subdir = path.join(dir, det.dir || ds.id);
      const written = await mapLimit(r.rows, 5, async (row) => {
        const id = row[det.idKey || 'id'];
        if (id == null) return false;
        try {
          const data = await callTool(det.detailTool, { [det.argKey || 'id']: id });
          const inner = data && typeof data === 'object' && 'data' in data ? data.data : data;
          const name = String(row[det.nameKey || 'name'] != null ? row[det.nameKey || 'name'] : id);
          writeJson(path.join(subdir, slugify(name) + '-' + String(id).slice(0, 8) + '.json'), inner);
          return true;
        } catch { return false; }
      });
      console.log('  ' + dept.id + '/' + (det.dir || ds.id) + '/: ' + written.filter(Boolean).length + ' detail files');
    }
  }
  if (!onlyDataset) {
    for (const ref of dept.references || []) {
      try {
        const data = await callTool(ref.tool, ref.args || {});
        const inner = data && typeof data === 'object' && 'data' in data ? data.data : data;
        writeJson(path.join(dir, ref.id + '.json'), inner != null ? inner : {});
        console.log('  ' + dept.id + '/' + ref.id + ': reference ok');
      } catch (err) {
        console.log('  ' + dept.id + '/' + ref.id + ': ERROR ' + String(err && err.message ? err.message : err).slice(0, 120));
      }
    }
  }
  try { writeDeptDocs(dept); } catch { /* docs are best-effort */ }
  return status;
}

function deptFreshness(deptId) {
  const dir = path.join(DATA, deptId);
  if (!existsSync(dir)) return null;
  let newest = null;
  const dept = manifest.departments.find((d) => d.id === deptId);
  for (const ds of (dept && dept.datasets) || []) {
    const f = path.join(dir, ds.id + '.json');
    if (!existsSync(f)) continue;
    try {
      const at = JSON.parse(readFileSync(f, 'utf8')).fetched_at;
      if (at && (!newest || at > newest)) newest = at;
    } catch { /* unreadable snapshot = treat as missing */ }
  }
  return newest;
}

// ── CLI ──────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const byId = new Map(manifest.departments.map((d) => [d.id, d]));
function usage() {
  console.log('Departments (* = your defaults): ' + manifest.departments.map((d) => (manifest.default_departments.includes(d.id) ? d.id + '*' : d.id)).join(' '));
  console.log('Usage: node .hiveku/pull-data.mjs <dept ...> | --default | --all | --stale [hours] | --dataset <dept:id> | --list');
}
async function main() {
  let targets = [];
  let onlyDataset = null;
  if (argv.includes('--list') || argv.length === 0) {
    for (const d of manifest.departments) {
      const fresh = deptFreshness(d.id);
      const mark = manifest.default_departments.includes(d.id) ? '*' : ' ';
      console.log(mark + ' ' + d.id.padEnd(12) + (fresh ? 'fetched ' + fresh : 'not downloaded'));
    }
    if (argv.length === 0) usage();
    return;
  }
  if (argv[0] === '--dataset') {
    const parts = String(argv[1] || '').split(':');
    const dept = byId.get(parts[0]);
    if (!dept || !parts[1]) { console.error('Expected --dataset <dept>:<dataset-id>'); usage(); process.exit(1); }
    if (!dept.datasets.some((ds) => ds.id === parts[1])) {
      console.error('Unknown dataset "' + parts[1] + '" for ' + dept.id + '. Valid: ' + dept.datasets.map((ds) => ds.id).join(', '));
      process.exit(1);
    }
    targets = [dept]; onlyDataset = parts[1];
  } else if (argv.includes('--all')) {
    targets = manifest.departments;
  } else if (argv.includes('--default')) {
    targets = manifest.default_departments.map((id) => byId.get(id)).filter(Boolean);
  } else if (argv.includes('--stale')) {
    const idx = argv.indexOf('--stale');
    const hours = Number(argv[idx + 1]) > 0 ? Number(argv[idx + 1]) : 12;
    const cutoff = new Date(Date.now() - hours * 3600000).toISOString();
    targets = manifest.default_departments.map((id) => byId.get(id)).filter(Boolean)
      .filter((d) => { const f = deptFreshness(d.id); return !f || f < cutoff; });
    if (!targets.length) { console.log('All default departments fresh (within ' + hours + 'h).'); return; }
  } else {
    const unknown = argv.filter((a) => !byId.has(a));
    if (unknown.length) { console.error('Unknown department(s): ' + unknown.join(', ')); usage(); process.exit(1); }
    targets = argv.map((a) => byId.get(a));
  }
  let statusAll = {};
  const statusFile = path.join(DATA, 'STATUS.json');
  try { statusAll = JSON.parse(readFileSync(statusFile, 'utf8')); } catch { statusAll = {}; }
  if (!statusAll.departments) statusAll.departments = {};
  let okDepts = 0;
  for (const dept of targets) {
    console.log(dept.label + ' (' + dept.id + ')');
    const st = await pullDept(dept, onlyDataset);
    const prev = statusAll.departments[dept.id];
    // A single-dataset refresh merges into the department entry, never replaces it.
    statusAll.departments[dept.id] = onlyDataset && prev && prev.datasets
      ? { fetched_at: st.fetched_at, datasets: Object.assign({}, prev.datasets, st.datasets) }
      : st;
    const errs = Object.values(st.datasets).filter((x) => x.error).length;
    const total = Object.keys(st.datasets).length;
    // total === 0 = references-only department — references log their own errors.
    if (total === 0 || total > errs) okDepts++;
  }
  statusAll.updated_at = new Date().toISOString();
  statusAll.runner_version = ${RUNNER_VERSION};
  writeJson(statusFile, statusAll);
  if (targets.length && okDepts === 0) { console.error('Every dataset failed — check the account key in .mcp.json.'); process.exit(1); }
  console.log('Done. Data in hiveku-data/ — work from these local files; use live MCP tools for writes.');
}
main().catch((err) => { console.error(err && err.message ? err.message : err); process.exit(1); });
`;
}
