/**
 * Role-specific Claude Code slash commands, generated by the scaffold from the
 * account's role (roles.ts). Every role gets:
 *   /hiveku-daily        — morning brief: context → role signals → today's tasks
 *   /hiveku-new-command  — capture THIS account's process as a new account command
 *                          (saved locally AND to Hiveku via memory_create type=command)
 * plus up to two role loops. All commands share one skeleton: account_context_get
 * FIRST → do the work → persist learnings (memory) → reflect work in Hiveku PM
 * (source of truth). Writes are confirmed per-step, never auto-approved.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { ROLES, roleById, type Role } from './roles';
import { skillsForRole } from './agencySkills';

async function writeCmd(baseDir: string, name: string, body: string): Promise<void> {
  const file = path.join(baseDir, '.claude', 'commands', `${name}.md`);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, body, 'utf8');
}

function mcp(tools: string[]): string {
  return tools.map((t) => `mcp__hiveku__${t}`).join(', ');
}

const PERSIST_STEP =
  'Finish every session of work the same way: persist notable learnings to department memory ' +
  '(`memory_list` → `memory_create({ type: "memory", name: "<dept>", content })` or `memory_update`), ' +
  'and reflect the work in Hiveku PM — `pm_tasks_create`/`pm_tasks_update`/`pm_tasks_complete`. ' +
  'Hiveku, not this folder, is the source of truth.';

function dailyCommand(role: Role): string {
  const signals = role.briefTools;
  const domain = role.knowledgeDomains[0] ?? 'marketing';
  const readTools = ['account_context_get', ...signals, 'mc_tasks_next', 'pm_tasks_list', 'memory_list', 'memory_create', 'memory_update'];
  return `---
description: Morning brief for this account (role: ${role.label}) — context, signals, then today's tasks. Pass a department to focus this session elsewhere.
argument-hint: "[department, optional — e.g. ppc, seo, sales]"
allowed-tools: ${mcp([...new Set(readTools)])}
---
Run my morning brief for this account. Role: **${role.label}**.

**Session focus:** if "$ARGUMENTS" names a department (e.g. ppc, seo, sales, outbound, content),
THIS SESSION works that department instead of the default role: use that domain for
\`account_context_get\`, pull that department's signals (its hiveku-*-agency skill has the list),
and prefix your first reply with "Working <account> — <department>" so parallel sessions are
unmistakable. Otherwise proceed with the role below.

1. Load context FIRST: \`account_context_get({ domain: "${domain}" })\` — re-read its \`instructions\`.
   **If the context comes back essentially EMPTY** (no brand guide, no avatars, no memory — a
   not-yet-onboarded account), STOP the brief and tell the user to run \`/hiveku-onboard\` — a
   brief with no foundation produces generic junk.
2. Pull the signals (skip any tool that errors with an entitlement/plan message):
${signals.map((t) => `   - \`${t}\``).join('\n')}
3. End with the task queue: \`mc_tasks_next\` then \`pm_tasks_list\` (open, due soon).
4. Report: a 5-line summary, then the top 3 actions ranked by impact. Keep it tight.
5. ${PERSIST_STEP} Offer (do not force) to create a PM task per recommended action.
`;
}

const ONBOARD_COMMAND = `---
description: Onboard this account like an agency's month-1 — assess, research, populate the brand/avatar/journey foundation, baseline every discipline, and create the engagement plan.
argument-hint: "[business website URL, optional]"
---
Run the agency onboarding for this account. You do the RESEARCH and the POPULATING — the user
answers questions, approves, and connects OAuth things only they can.

## Phase 0 — Assess (always start here)
\`get_account_info\` (identity check) → \`account_audit_health({ account_id })\` (drift flags like
no_memory_entries) → \`onboarding_read\` (dashboard onboarding state) → \`brand_guide_list\` +
\`customer_avatar_list\` + \`customer_journey_list\` + \`memory_list\`.
Classify: **RAW** (no brand guide, no avatars, empty memory) / **PARTIAL** (some exist) /
**ONBOARDED** (foundation present). Report what you found before doing anything.

## Phase 1 — Foundation (RAW: build it; PARTIAL: fill only the gaps)
1. **Research first.** Scrape the business site ($ARGUMENTS or ask for the URL): \`web_scrape\` the
   homepage, /about, and 2-3 service/product pages; \`web_search\` the brand + its competitors.
   Then interview the user for what scraping can't know: who the best customers are, the offer and
   pricing model, tone dos/don'ts, competitors they respect, goals for the next quarter.
2. **Seed in ONE call:** \`account_seed_initialize({ brand_guide, avatars: [2-3 specs],
   journeys: [1-2 specs] })\` — names + one-line summaries are enough; enrichment comes next.
3. **Enrich GROUNDED:** per avatar \`customer_avatar_populate({ entity_id, urls_to_scrape: [their
   homepage, /about, service pages], agent_notes: <your interview notes> })\`; per journey
   \`customer_journey_populate\` the same way. These tools refuse without grounding — that is why
   research came first.
4. **Seed department memory:** for each discipline this account will run, write the operating
   facts you learned — \`memory_create({ type: "memory", name: "<dept>", content })\` (ICP summary,
   offer, voice notes, competitors, constraints). This is what makes every future
   \`account_context_get\` call rich instead of empty.
5. Show the user what you built (brand voice line, avatar names, journey stages) and refine on
   their feedback (\`brand_guide_update\`, \`customer_avatar_update\`).

## Phase 2 — Connections + baselines (per discipline the account runs)
For each active department, follow its \`hiveku-data/<dept>/SETUP.md\` playbook for connections
(GSC, ad accounts, email domain, Smartlead/HeyReach are dashboard-only — hand the user the exact
steps), then capture the baseline: SEO \`seo_run_audit\` + \`seo_sync\`; PPC
\`ppc_conversion_tracking_status\` + \`ppc_metrics\`; email \`email_stats\`; sales
\`crm_pipeline_stage_summary\`; outbound \`outbound_list_campaigns\`. Baselines are what month-2
reports get compared against — persist them to memory.

## Phase 3 — Engagement plan
Create the PM engagement: \`pm_projects_create({ name: "<Account> — <discipline> engagement",
project_type })\` + \`pm_tasks_create_bulk\` with the first month's plays (from the
hiveku-*-agency skills' month-1 sections), each with a due date. Offer to schedule the cadence
("Hiveku: Install Agency Cadence" gives the user automated daily briefs + weekly passes).

Confirm every write. When done, run \`/hiveku-daily\` to prove the account now briefs properly.
`;

const NEW_SITE_COMMAND = `---
description: Spin up a NEW website project for this account — from a template, then inject sections.
argument-hint: "[what kind of site — e.g. 'a plumber landing page']"
---
Create a new site project for THIS account$ARGUMENTS. You do the build; the human approves.

1. Pick a starting point: \`templates_list({ category?, search? })\` (70+ site templates) — read \`template_get({ slug })\` for the one that fits, or start blank.
2. Create it: \`site_create({ name, project_type: "website", creation_mode, template_id?, domain? })\` → returns the new project_id. (Clone an existing one instead with \`site_clone({ project_id, new_name })\`; register an already-hosted site with \`site_create_external({ name, external_website_url })\`.)
3. Add sections: \`components_list({ category?, intent?, style?, search? })\` (~220 prebuilt sections) → \`components_add({ project_id: <new id>, components: [...], dry_run: true })\` first to preview, then for real — it injects each section's files + resolves npm deps.
4. Download it locally to keep building: tell the user to run "Hiveku: Download Project" (or open it from the Projects tree), then /hiveku-verify + /hiveku-deploy development.
5. Point a domain at it with /hiveku-domains (in the site's folder) and configure the CMS with /hiveku-cms.
Confirm before \`site_create\`/\`site_delete\` (delete is irreversible + drops any Supabase billing). Reflect the new project as a PM task if this is client work.
`;

const RESEARCH_COMMAND = `---
description: Deep web research for this account — competitors, content gaps, prospects — via the Firecrawl ladder.
argument-hint: "[what to research — e.g. 'competitor pricing pages']"
---
Research$ARGUMENTS for THIS account. Escalate only as far as you need — each rung costs more:

1. \`web_search({ query, count?, country?, freshness? })\` — find candidate URLs / answer a quick question.
2. \`web_scrape({ url, formats: ["markdown"] })\` — one page's content (the workhorse).
3. \`web_map({ url, search? })\` — enumerate a whole site's URLs (find every /pricing, /service page).
4. \`web_crawl({ url, limit })\` — pull many pages of a site at once (competitor content audit).
5. \`web_extract({ urls: [...], schema | prompt })\` — pull STRUCTURED JSON across many URLs (e.g. {price, plan} from every competitor pricing page) — the highest-leverage rung for comparison tables.
6. \`web_actions({ url, actions: [...] })\` — click/scroll/fill to reach content behind interaction.
Persist what you find to department memory (\`memory_create\`) and, for SEO/content, feed it into content-gap + keyword work. Cite source URLs in your summary; never fabricate a finding.
`;

const CONNECT_COMMAND = `---
description: Connect or re-connect this account's ad/SEO integrations (Google Ads, GSC, GA, Bing) end-to-end.
argument-hint: "[what to connect: google-ads | gsc | ga | bing | all]"
---
Be the integration operator for THIS account$ARGUMENTS. You do the whole Hiveku side; the human does
exactly TWO things — a one-time cloud app, and one consent click. Never ask them to run MCP tools.

SHARED CREDENTIALS (BYOK, reused across every account): read the agency OAuth client from
\`../.env.locus.wide-access\` (fleet root) or \`./.env.locus.wide-access\` (this folder). It holds
GOOGLE_ADS_CLIENT_ID / GOOGLE_ADS_CLIENT_SECRET / GOOGLE_ADS_DEVELOPER_TOKEN / MICROSOFT_ADS_CLIENT_ID /
MICROSOFT_ADS_CLIENT_SECRET. If it is missing, tell the user to create it (format is in the account
CLAUDE.md) — one client serves every account, so this is a one-time paste.

STEP 1 — DIAGNOSE (always first). Call \`ppc_connection_list\` (Google/Bing Ads), \`seo_connections_list\`
(GSC, GBP, Bing Webmaster) and \`integration_list\`. For each, report status + last_error:
"Token refresh failed" / "Account has been deleted" = DEAD TOKEN → re-auth IN PLACE (keeps the
connection's history + binding). "must have gbp_account_id/location" = a binding fix, not auth. Capture
each connection's \`id\` (you need it as target_connection_id).

STEP 2 — ENSURE AN OAUTH APP for the product. \`oauth_app_list\`. If none covers the product you need,
\`oauth_app_create({ provider, name, client_id, client_secret, products:[<slug>] })\` with the shared
client (provider "google" for google_* ; "microsoft" for microsoft_ads). One Google client can back
google_ads + google_search_console + google_analytics — one app per product slug is fine.

STEP 3 — INITIATE. This SPLITS by provider — the paths are NOT the same:
  A) GOOGLE (google_ads, google_search_console, google_analytics, google_gmail, google_calendar) — CLI
     OAuth works: \`integration_oauth_initiate({ provider_slug, target_connection_id: <id>, oauth_app_id })\`
     (re-auth in place keeps data) → returns a \`setup_url\` the human clicks. First Google Ads connect:
     add customer_id / manager_id / developer_token from the shared file.
  B) BING WEBMASTER (organic search — the GSC equivalent) — NO OAuth. It's an SEO connection with just an
     API key: \`seo_connection_create({ platform: "bing_webmaster", site_url, api_key })\` (key from
     bing.com/webmasters → Settings → API access; the site can be one-click "Import from Google Search
     Console" there). Then \`seo_sync\` + \`seo_bing_stats\` to verify. Do NOT use integration_oauth_initiate
     or integration_create for Bing Webmaster — both reject it ("Unknown provider_slug").
  C) BING ADS (microsoft_ads) — CLI OAuth is NOT supported (integration_oauth_initiate is Google-only).
     Register the Azure app once (\`oauth_app_create({ provider: "microsoft", products: ["microsoft_ads"],
     client_id, client_secret })\`), then the human connects it in the DASHBOARD:
     \`https://app.hiveku.com/<accountId>/dashboard/marketing/ppc\` (the account-scoped URL — never a bare
     /dashboard/ path). After they connect, you pick it up with ppc_connection_list. Bing Ads writes are
     limited to pause/enable/budget (\`ppc_platform_*\`); no keyword/RSA/asset writes; ad-groups/ads don't sync.

STEP 4 — HAND THE HUMAN THE ONE CLICK. Print the setup_url and say: open it in the browser signed into
the account that has access (the MCC login for Ads, the Search Console owner for GSC) and click Allow.
Name the scope requested. It reuses the shared client + one redirect URI, so once the cloud app is set
up right, every account is just this click.

STEP 5 — POLL. Every ~5s call \`integration_oauth_check({ setup_token })\` until status="completed"
(integration_id present) or "error"/expired. Don't spin silently — tell the user you're waiting.

STEP 6 — SYNC + VERIFY + REPULL. On success: Ads → \`ppc_sync({ connection_id })\` then
\`ppc_connection_test\`; SEO → \`seo_sync\` then \`seo_connections_list\`. Confirm status flips to connected
and data returns, then refresh local files: \`node .hiveku/pull-data.mjs ppc\` (or seo / localseo).

THE HUMAN'S ONLY TWO JOBS (state them, and that everything else is you):
  1. ONE-TIME cloud app (per provider, reused for ALL accounts): a Google Cloud "Web application" OAuth
     client (on Workspace, set it INTERNAL so tokens never expire), the Google Ads / Search Console API
     enabled, with this EXACT Authorized redirect URI — in "Authorized redirect URIs", NOT "JavaScript
     origins":
       Google:    https://app.hiveku.com/api/oauth/google/callback
       Microsoft: https://app.hiveku.com/api/oauth/microsoft/callback
     Then paste the client id/secret into .env.locus.wide-access.
  2. ONE consent click per account (step 4).

THE #1 FAILURE — "Error 400: redirect_uri_mismatch": the exact redirect URI above is NOT on the client's
Authorized redirect URIs (added to the wrong client, or to JavaScript origins, or not Saved). Have the
user add it to the SAME client whose id appears in the setup_url, Save, wait ~2 min, then re-run this
command for a fresh link. If Ads already connected on this client, GSC/GA reuse it with no new URI.
GOTCHA: Testing-mode external apps expire refresh tokens after 7 days (why connections silently die) —
Internal (Workspace) apps do not. Bing WEBMASTER = seo_connection_create (API key, no OAuth); Bing ADS =
Azure app + dashboard connect at /<accountId>/dashboard/marketing/ppc (CLI OAuth is Google-only).
`;

const PULL_DATA_COMMAND = `---
description: Pull/refresh this account's department data into hiveku-data/ so you can work on LOCAL files.
argument-hint: "[departments, e.g. seo ppc — or --stale / --all]"
---
Refresh the local data mirror$ARGUMENTS, then work from the files — not from repeated live list calls.

1. Run the runner from this folder (deterministic bulk export; rows never pass through your context):
   - \`node .hiveku/pull-data.mjs --list\` — see departments + freshness
   - \`node .hiveku/pull-data.mjs <dept ...>\` — pull what you need (e.g. \`seo ppc\`)
   - \`node .hiveku/pull-data.mjs --stale 12\` — refresh your role's departments older than 12h
   - \`node .hiveku/pull-data.mjs --dataset <dept>:<dataset>\` — re-pull ONE dataset (do this right after you write)
2. Then analyze LOCALLY: grep/read \`hiveku-data/<dept>/*.json\` (each file is
   { dataset, count, fetched_at, rows } — check fetched_at before trusting it). Scoped rows carry
   \`_parent\` (which project/connection they came from).
3. The local-first loop:
   - READ from hiveku-data/ (fast, free, greppable).
   - WRITE via the live MCP tools (the write path is in each department's README.md + SETUP.md).
   - After a write that changes a dataset, re-pull just that dataset with --dataset so local stays true.
4. If the runner errors on every dataset, this account's key is no longer valid — tell the user to
   run "Hiveku: Connect Hiveku" for this account (never open or print the key file). Per-dataset
   errors are normal for unconnected integrations (see the dept SETUP.md).
`;

const NEW_COMMAND = `---
description: Capture one of THIS account's processes as a reusable account command (synced to Hiveku, per department).
argument-hint: "[what the command should do]"
---
Create a new account-specific slash command$ARGUMENTS. Every account works differently — this is how
its way of working gets codified once and shared with every operator AND the dashboard agents.

1. Capture the process: either the workflow you JUST performed in this conversation, or the
   procedure the user describes. Ask for the missing specifics (constraints, thresholds,
   approvals) — account commands encode THEIR rules, not generic ones.
2. Draft the command as markdown:
   - \`---\\ndescription: <one line>\\n---\` frontmatter (no allowed-tools — leave approvals explicit),
   - numbered steps with EXACT Hiveku tool names (verify via \`hiveku_docs_search\` if unsure),
   - "confirm before each write" notes where the process mutates data,
   - \`$ARGUMENTS\` where inputs vary per run,
   - an HTML comment tag \`<!-- department: <dept> -->\` near the top (e.g. ppc, seo, sales, accounting).
3. Pick a kebab-case slug (e.g. \`ppc-weekly-tune\`). Save it BOTH places with IDENTICAL content:
   - locally: \`.claude/commands/hiveku-<dept>-<slug>.md\` (usable immediately as a slash command),
   - to Hiveku: \`memory_create({ type: "command", name: "<slug>", content })\` — on a 409, use
     \`memory_update\` instead.
4. Tell the user: the command now syncs to every operator of this account ("Hiveku: Download
   Everything" / Check Knowledge Sync) and is visible in the dashboard under its department.
To EDIT an account command later, change the Hiveku entry (\`memory_update\`) — Hiveku is the
source of truth; local edits to synced files are skipped by sync and reported.
`;

/** Per-role loop commands. Keyed by command name (without the hiveku- prefix). */
function roleLoops(role: Role): Record<string, string> {
  switch (role.id) {
    case 'seo':
      return {
        'hiveku-seo-fix': `---
description: Audit this account's site, fix the top SEO issues, track the keywords.
argument-hint: "[site or focus, optional]"
---
SEO fix loop$ARGUMENTS. Context first: \`account_context_get({ domain: "seo" })\`.
1. \`seo_run_audit\` (or latest \`seo_list_audits\` → \`seo_audit_get\`) → rank issues by impact.
2. Fix the top issues: if the site project is downloaded in this workspace, edit the files locally
   (then \`/hiveku-commit\` + \`/hiveku-deploy development\`); otherwise use the live tools
   (\`pages_update\`, \`cms_*\`, \`seo_schema_markup\`). Confirm before each write.
3. Track new targets: \`seo_track_keyword\`. Re-run the audit to verify the score moved.
4. ${PERSIST_STEP}
`,
        'hiveku-seo-decay': `---
description: Find decaying + cannibalizing content and produce a refresh plan.
---
Content decay sweep. Context: \`account_context_get({ domain: "seo" })\`.
1. \`seo_content_decay\` + \`seo_cannibalization\` → pages losing traffic or competing with themselves.
2. For the top candidates, get a brand-aligned refresh plan: \`talk_to_department({ domain: "seo", message })\`.
3. Create one PM task per refresh (\`pm_tasks_create\`) with the plan in the description.
4. ${PERSIST_STEP}
`,
      };
    case 'ppc':
      return {
        'hiveku-ppc-optimize': `---
description: Optimization pass — search terms to negatives, pacing, disapprovals. Confirms every write.
---
PPC optimization pass. Context: \`account_context_get({ domain: "ppc" })\`.
1. \`ppc_search_terms_report\` → wasted-spend queries → propose negatives; on approval
   \`ppc_negative_keyword_add\` (confirm EACH — never bulk-apply silently).
2. \`ppc_pacing_summary\` → over/under-pacing campaigns → propose \`ppc_budget_update\` changes (confirm each).
3. \`ppc_disapprovals_list\` → fixes per disapproved ad.
4. Respect account rules from context/memory (e.g. protected brand campaigns, approval thresholds).
5. ${PERSIST_STEP}
`,
        'hiveku-ppc-report': `---
description: Period-over-period ads report — winners, losers, spend story.
argument-hint: "[days, default 28]"
---
PPC report for the last $ARGUMENTS days (default 28). Context: \`account_context_get({ domain: "ppc" })\`.
1. \`ppc_period_comparison\` + \`ppc_metrics\` + \`ppc_digest\` → winners/losers, CPC movers, conv trends.
2. Write a short client-readable memo (plain language, numbers that matter, next tests).
3. ${PERSIST_STEP}
`,
      };
    case 'bookkeeper':
      return {
        'hiveku-books-close': `---
description: Work the books — AP/AR aging, approve queue, exceptions to PM. Confirms every approval.
---
Books pass. 1. \`accounting_ap_aging\` + \`accounting_ar_aging\` + \`accounting_pnl_summary\` — the state.
2. \`accounting_bill_list({ status: "submitted" })\` → walk the approve queue: show each bill
   (vendor, amount, due), get explicit approval, then \`accounting_bill_approve\` — ONE at a time.
3. Anything odd (duplicate vendor, missing terms, unusual amount) becomes a PM task, not a guess.
4. Record payments only when told: \`accounting_bill_record_payment\` (confirm).
5. ${PERSIST_STEP}
`,
        'hiveku-books-chase': `---
description: Chase overdue receivables — reminders drafted per invoice, activity logged.
---
AR chase. 1. \`accounting_ar_aging\` + \`accounting_invoice_list({ status: "all" })\` → overdue invoices.
2. Per overdue invoice, draft a firm-but-brand-aligned reminder via
   \`talk_to_department({ domain: "sales", message })\`. Show drafts — do NOT send anything without approval.
3. Log each chase as an activity (\`crm_create_activity\`) and record promised dates as PM tasks.
4. ${PERSIST_STEP}
`,
      };
    case 'pm':
      return {
        'hiveku-standup': `---
description: Standup — what's next, breached, stalled, and milestone health.
allowed-tools: mcp__hiveku__mc_tasks_next, mcp__hiveku__mc_sla_breached, mcp__hiveku__mc_tasks_stalled, mcp__hiveku__pm_milestones_list, mcp__hiveku__pm_tasks_list, mcp__hiveku__memory_create, mcp__hiveku__memory_update, mcp__hiveku__memory_list
---
Standup. 1. \`mc_tasks_next\` (the queue) + \`mc_sla_breached\` + \`mc_tasks_stalled\` + \`pm_milestones_list\`.
2. Report per project: on-track / at-risk / blocked, with the ONE next action each.
3. Save the standup note to memory (name "workflow"). ${PERSIST_STEP}
`,
        'hiveku-triage': `---
description: Triage pending intake — classify, assign, transition.
---
Triage pass. 1. \`mc_tasks_list\` (pending/unassigned) → for each, \`mc_intake_classify\` if unclassified.
2. Propose assignee + lane + priority; on approval \`mc_task_update\` / \`mc_task_transition\` (confirm each).
3. Anything needing a human decision → \`mc_task_decide\` queue, flagged in the summary.
4. ${PERSIST_STEP}
`,
      };
    case 'marketer':
      return {
        'hiveku-campaign': `---
description: Plan + draft a campaign with the account's brand context, then schedule it.
argument-hint: "[campaign brief]"
---
Campaign: $ARGUMENTS. Context FIRST: \`account_context_get({ domain: "marketing" })\`.
1. Strategy + copy through the department agents (full brand/memory):
   \`talk_to_department({ domain: "marketing", message })\` then \`{ domain: "content" }\` for drafts.
2. Persist: \`content_create\` per asset; schedule with \`content_schedule\` / \`email_campaign_create\`
   (confirm before anything is scheduled to SEND).
3. Create the campaign's PM tasks. ${PERSIST_STEP}
`,
        'hiveku-email': `---
description: Build, test and launch an email campaign end-to-end - audience, content, template, test send, schedule/send. Alpha-aware.
argument-hint: "[what the campaign is about]"
---
Build and launch an email campaign: $ARGUMENTS. Email marketing is ALPHA in Hiveku - after every
write, VERIFY by reading back (get/list) before proceeding; report failures verbatim, never assume.

1. Foundation check: \`email_domain_list\` (a VERIFIED sending domain is non-negotiable - if none,
   stop and run the Email SETUP playbook) and \`email_connections_list\`.
2. Audience: \`email_audience_list\` - pick or create (\`email_audience_create\` +
   \`email_audience_members_add\`; source contacts from \`crm_list_contacts\` filters). State the
   audience SIZE before anything sends.
3. Content: \`account_context_get({ domain: "marketing" })\` FIRST, then draft via
   \`talk_to_department({ domain: "content", message })\` - subject (<50 chars) + preview text +
   HTML body + plain text. Reuse or save a template (\`email_template_list\` / \`email_template_create\`).
4. Create the DRAFT: \`email_campaign_create({ name, subject, from_email, audience_id, ... })\` -
   from_email must be on the verified domain. Read it back with \`email_campaign_get\`.
5. TEST FIRST - never skip: \`email_campaign_test_send({ id, to: [the user's email] })\`. Ask the
   user to confirm the render looks right before ANY real send.
6. Launch only on explicit approval: \`email_campaign_schedule({ id, scheduled_for })\` (ISO time,
   respect the audience timezone) or \`email_campaign_send_now({ id })\`. Confirm which one.
7. Manage after: \`email_campaign_metrics({ id })\` next day - report delivered/opens/clicks/bounces;
   pause/resume/cancel via the matching tools; winners get \`email_campaign_resend_non_openers\`.
8. ${PERSIST_STEP}
`,
        'hiveku-email-review': `---
description: Email program review — stats, winners/losers, next test.
---
Email review. 1. \`email_stats\` + \`email_campaign_list\` → \`email_campaign_metrics\` for recent sends.
2. Winners/losers by open/click/conversion; ONE next A/B test recommendation with rationale.
3. ${PERSIST_STEP}
`,
      };
    case 'sales':
      return {
        'hiveku-pipeline': `---
description: Pipeline pass — at-risk and stuck deals, one next step each.
---
Pipeline pass. Context: \`account_context_get({ domain: "sales" })\`.
1. \`crm_deals_at_risk\` + \`crm_deals_stuck\` + \`crm_pipeline_stage_summary\`.
2. Per deal: the ONE next step (call, email, proposal) — log it as \`crm_create_activity\` and, where
   a follow-up is due, a PM task with the due date.
3. ${PERSIST_STEP}
`,
        'hiveku-followups': `---
description: Re-engage gone-cold contacts with brand-aligned drafts. Nothing sends without approval.
---
Follow-ups. 1. \`crm_contacts_gone_cold\` → prioritize by lead_score/deal value.
2. Draft re-engagement per contact via \`talk_to_department({ domain: "outbound", message })\`.
3. Show drafts. Only on explicit approval: \`crm_enroll_sequence\` or send via the connected inbox.
4. Update \`crm_update_contact\` stages + log activities. ${PERSIST_STEP}
`,
      };
    case 'outbound':
      return {
        'hiveku-replies': `---
description: Triage new Smartlead/HeyReach replies — classify, draft, update leads + CRM. Idempotent.
---
Reply triage. Context: \`account_context_get({ domain: "outbound" })\`.
1. Get new replies: if the local automations worker runs here, read its state/log under
   \`automations/\`; else pull from Smartlead/HeyReach REST (keys in \`automations/.env\`;
   endpoints in \`.claude/AUTOMATION.md\`). Track handled reply ids — never process one twice.
2. Classify each: interested / question / objection / unsubscribe / bounce.
3. Interested + questions: draft replies via \`talk_to_department({ domain: "outbound", message })\` —
   show drafts, do NOT send without approval.
4. Persist EVERY reply: \`outbound_update_lead({ lead_id, is_interested, internal_status })\` +
   \`crm_contact_upsert_by_email\` + \`crm_create_activity\` (the reply + your draft).
5. Unsubscribes → \`crm_set_dnc\` immediately. ${PERSIST_STEP}
`,
        'hiveku-outbound-health': `---
description: Outbound program health — campaign stats, reply/bounce rates, list quality, next actions.
---
Outbound health. 1. \`outbound_list_campaigns\` + per-campaign \`outbound_list_leads\` counts by
\`internal_status\` / \`has_replied\` / \`is_interested\` → reply rate, positive rate, bounce signals.
2. \`email_stats\` for the sending side; \`crm_contacts_gone_cold\` for the re-engagement pool.
3. Top 3 actions (kill/scale campaigns, list hygiene, copy tests) → PM tasks on approval.
4. For continuous coverage, point the user at the local reply-triage automation
   (\`.claude/AUTOMATION.md\`, \`node automations/manage.mjs list\`). ${PERSIST_STEP}
`,
      };
    case 'helpdesk':
      return {
        'hiveku-tickets': `---
description: Work the overdue ticket queue with macro-based drafts. Nothing sends without approval.
---
Ticket pass. 1. \`helpdesk_tickets_overdue\` → queue by priority/age.
2. Per ticket: \`helpdesk_ticket_get\` + \`helpdesk_ticket_messages\` for context; find a fitting macro
   (\`helpdesk_macros_list\` → \`helpdesk_macros_render\`) or draft fresh; check \`helpdesk_kb_search\`
   for citable articles.
3. Show each draft; on approval \`helpdesk_ticket_send_reply\` + status via \`helpdesk_ticket_set_status\`.
4. ${PERSIST_STEP}
`,
        'hiveku-kb-gaps': `---
description: Find knowledge-base gaps from ticket themes + CSAT, draft the missing articles.
---
KB gap sweep. 1. \`helpdesk_csat_stats\` + recent \`helpdesk_ticket_list\` → recurring themes with no
KB coverage (\`helpdesk_kb_search\` per theme).
2. Draft the missing articles (\`helpdesk_kb_suggest_articles\` where available, else write them) →
   \`helpdesk_kb_article_create\` as DRAFTS for review.
3. ${PERSIST_STEP}
`,
      };
    case 'social':
      return {
        'hiveku-social-plan': `---
description: Plan a week of posts from pillars + analytics, drafted on-brand.
---
Social week plan. Context: \`account_context_get({ domain: "social" })\`.
1. \`social_analytics_summary\` (what worked) + \`social_pillar_list\` (what we stand for).
2. Draft the week via \`talk_to_department({ domain: "social", message })\` — per-platform variants.
3. Persist as DRAFTS: \`social_create_post\` (scheduled times proposed, publishing only on approval).
4. ${PERSIST_STEP}
`,
        'hiveku-social-report': `---
description: Social performance report — by platform, by pillar, next bets.
---
Social report. 1. \`social_analytics_summary\` + \`social_list_posts\` (recent, with metrics).
2. By platform and pillar: what over/under-performed; 3 next bets.
3. ${PERSIST_STEP}
`,
      };
    default:
      return {};
  }
}

/**
 * Weekly optimization pass + monthly client-grade report for the agency
 * disciplines (SEO, PPC, content, sales, outbound). Both defer methodology to
 * the role's hiveku-*-agency SKILL (auto-loaded by Claude Code) and stay short.
 */
function cadenceCommands(role: Role): Record<string, string> {
  const spec: Partial<Record<Role['id'], { skill: string; weekly: string; report: string }>> = {
    seo: {
      skill: 'hiveku-seo-agency',
      weekly: 'rank movements (`seo_rankings_list`), GSC anomalies (`seo_gsc_period_comparison`), new/lost links (`seo_new_lost_backlinks`), audit deltas, this week\'s publish/refresh pipeline',
      report: 'build the report as a Hiveku deliverable: `seo_deliverable_save({ title, slug, deliverable_type: "monthly_report", target_domain })`, then `seo_report_add_section` per section (executive summary, rankings movement, traffic, work completed, next month plan)',
    },
    ppc: {
      skill: 'hiveku-ppc-agency',
      weekly: 'search-term mining (`ppc_search_terms_report` → negatives), pacing (`ppc_pacing_summary` → budget moves), anomalies (`ppc_anomaly_check`), disapprovals, test readouts',
      report: 'pull `ppc_period_comparison` + `ppc_metrics` + `ppc_digest` + `ppc_change_history`; write the client memo (spend vs results vs target, what changed, tests concluded, next month plan) to `reports/<YYYY-MM>-ppc.md`',
    },
    marketer: {
      skill: 'hiveku-content-agency',
      weekly: 'pipeline review (drafted/scheduled/published via `content_list`), last week\'s piece performance (`analytics_pages`, `social_analytics_summary`, `email_campaign_metrics`), next week\'s calendar',
      report: 'published inventory + per-piece performance + avatar/journey coverage map + next month calendar → `reports/<YYYY-MM>-content.md`',
    },
    social: {
      skill: 'hiveku-content-agency',
      weekly: 'last week\'s post performance (`social_analytics_summary`, `social_list_posts`), pillar balance, next week\'s queue',
      report: 'by-platform and by-pillar performance + next bets → `reports/<YYYY-MM>-social.md`',
    },
    sales: {
      skill: 'hiveku-sales-agency',
      weekly: 'pipeline movement (`crm_pipeline_stage_summary`, `crm_pipeline_velocity`), at-risk/stuck interventions, sequence health (`crm_sequence_analytics`), forecast check (`crm_forecast_weighted`)',
      report: 'pipeline created/advanced/won-lost, stage conversion (`crm_report_conversion_funnel`, `crm_report_stage_transitions`), activity health, forecast, focus list → `reports/<YYYY-MM>-sales.md`',
    },
    outbound: {
      skill: 'hiveku-outbound-agency',
      weekly: 'campaign-level funnel (sends/replies/positives via `outbound_list_campaigns` + `outbound_list_leads`), deliverability health (bounce/complaint watch), kill/scale calls, list burn',
      report: 'sends, replies, positives, meetings booked, pipeline created vs targets → `reports/<YYYY-MM>-outbound.md`',
    },
  };
  const s = spec[role.id] ?? (role.id === 'owner' ? { skill: 'the relevant hiveku-*-agency skills', weekly: 'each active discipline\'s weekly checklist', report: 'one consolidated report across disciplines → `reports/<YYYY-MM>-account.md`' } : undefined);
  if (!s) return {};
  return {
    'hiveku-weekly': `---
description: Weekly optimization pass (role: ${role.label}) — the agency cadence, not just a status check.
---
Run this account's weekly pass. Follow the **${s.skill}** skill's weekly cadence.
1. Context first: \`account_context_get({ domain: "${role.knowledgeDomains[0]}" })\`.
2. Work the checklist: ${s.weekly}.
3. Every change is confirmed before applying; every work item lands as a PM task.
4. Close with a 5-line "what changed / what's next" note → \`memory_create\`/\`memory_update\` (name "${role.knowledgeDomains[0]}").
`,
    'hiveku-report': `---
description: Monthly client-grade report (role: ${role.label}) — what an agency sends its clients.
argument-hint: "[month, default last month]"
---
Produce this account's monthly report for $ARGUMENTS (default: last full month). Follow the
**${s.skill}** skill's report structure.
1. Context: \`account_context_get({ domain: "${role.knowledgeDomains[0]}" })\` — write in the brand's voice, for the CLIENT (plain language, numbers that matter, no tool names).
2. ${s.report}.
3. Sections every agency report needs: executive summary (3 bullets), results vs last period, work completed, insights, next month's plan.
4. Persist the summary to memory and create next month's plan as PM tasks (on approval).
5. OFFER to email it to the client: render the report as clean simple HTML, then
   \`email_send_test({ to, subject, html_body, dry_run: true })\` to validate (from-domain must be
   verified; suppressions respected), show the would-send preview, and send for real ONLY after the
   user explicitly approves the recipient and content. Never email anything unapproved.
`,
  };
}

/** Every loop-command filename any role can generate — used to clean up on role switch. */
function allLoopNames(): Set<string> {
  const names = new Set<string>(['hiveku-weekly', 'hiveku-report']);
  for (const r of ROLES) for (const name of Object.keys(roleLoops(r))) names.add(name);
  return names;
}

/**
 * Write the role's slash commands into <baseDir>/.claude/commands/, removing any
 * OTHER role's generated loop commands (exact known names only — synced account
 * commands and user files are never touched). Returns the names written.
 */
export async function writeRoleSlashCommands(baseDir: string, roleId: string | undefined): Promise<string[]> {
  // Universal regardless of role — the account CLAUDE.md teaches the local-first
  // loop unconditionally, so the command must exist even with no role set.
  await writeCmd(baseDir, 'hiveku-pull-data', PULL_DATA_COMMAND);
  await writeCmd(baseDir, 'hiveku-connect', CONNECT_COMMAND);
  await writeCmd(baseDir, 'hiveku-new-site', NEW_SITE_COMMAND);
  await writeCmd(baseDir, 'hiveku-research', RESEARCH_COMMAND);
  const role = roleById(roleId);
  if (!role) return ['hiveku-pull-data', 'hiveku-connect', 'hiveku-new-site', 'hiveku-research'];
  const loops = { ...roleLoops(role), ...cadenceCommands(role) };
  // Clean up loop commands from a previous role.
  const mine = new Set(Object.keys(loops));
  for (const stale of allLoopNames()) {
    if (mine.has(stale)) continue;
    await fs.rm(path.join(baseDir, '.claude', 'commands', `${stale}.md`), { force: true }).catch(() => undefined);
  }
  const names: string[] = [];
  await writeCmd(baseDir, 'hiveku-daily', dailyCommand(role));
  names.push('hiveku-daily');
  await writeCmd(baseDir, 'hiveku-new-command', NEW_COMMAND);
  names.push('hiveku-new-command');
  names.push('hiveku-pull-data');
  names.push('hiveku-connect');
  names.push('hiveku-new-site');
  names.push('hiveku-research');
  await writeCmd(baseDir, 'hiveku-onboard', ONBOARD_COMMAND);
  names.push('hiveku-onboard');
  for (const [name, body] of Object.entries(loops)) {
    await writeCmd(baseDir, name, body);
    names.push(name);
  }
  return names;
}

/**
 * Multi-session / multi-account rules for agency operators — included in every
 * scaffolded CLAUDE.md. One window = one account; sessions declare a department
 * focus; identity is verified before writes.
 */
export const MULTI_SESSION_BLOCK = `
### Running many sessions / many accounts (agency mode)
- **One window = one account.** This folder IS one Hiveku account (its key is in \`.mcp.json\`; the
  window title + title-bar color identify it). Never operate a different account from this window —
  open that account's own folder instead.
- **Start every session by declaring identity + focus.** First action: \`get_account_info\` — verify
  it returns THIS folder's account; then state "Working <account> — <department>" in your first
  reply. If the account doesn't match, STOP: a user-level \`hiveku\` MCP server is shadowing this
  folder's key — tell the user to run "Hiveku: Which Account Is This?" and fix it before ANY write.
- **Parallel sessions on the same account are fine — one department each.** Use
  \`/hiveku-daily <department>\` to focus a session (e.g. one session ppc, another seo). Keep each
  session's memory writes in its own department domain, and name report files per department.
- **Never two sessions on the same website project's files.** Live-data work (CRM, ads, tickets)
  parallelizes safely; file edits + commits + deploys to the SAME project must stay in ONE session
  (last commit wins — you'd clobber the sibling's edits).
- **When in doubt, re-verify before writing:** \`get_account_info\` is one cheap call; a write to the
  wrong tenant is an incident.
`;

/** Compact role block for the scaffolded CLAUDE.md (inside the marker-managed section). */
export function roleClaudeMdBlock(roleId: string | undefined): string {
  const role = roleById(roleId);
  if (!role) return '';
  const loops = Object.keys({ ...roleLoops(role), ...cadenceCommands(role) });
  const skills = skillsForRole(roleId);
  return `
### Your role here: ${role.label}
Daily loop: start with \`/hiveku-daily\` (context → ${role.blurb.toLowerCase()} → today's tasks).
${loops.length ? `Role commands: ${loops.map((l) => `\`/${l}\``).join(' · ')}.` : ''}
${
  skills.length
    ? `**Agency methodology:** the ${skills.map((s) => `\`${s}\``).join(' + ')} skill${skills.length > 1 ? 's' : ''} in \`.claude/skills/\` ` +
      'carry the full engagement playbook — research, strategy, execution plays with exact tool chains, weekly cadence, ' +
      'monthly reporting, benchmarks. Follow them for any substantive work; `/hiveku-weekly` and `/hiveku-report` run the cadence.'
    : ''
}
Work LOCAL-FIRST: \`/hiveku-pull-data\` (or \`node .hiveku/pull-data.mjs --stale 12\`) refreshes
\`hiveku-data/\` yourself — read those files instead of re-listing live; write via MCP, then re-pull
the affected dataset with \`--dataset <dept>:<id>\`.
Connect ad/SEO platforms with \`/hiveku-connect\` — it drives the whole OAuth flow (diagnose → register
shared client → consent link → poll → sync → verify); the human just clicks one consent link.
New site: \`/hiveku-new-site\` (template → site_create → inject sections). Deep web research: \`/hiveku-research\`
(web_search → scrape → map → crawl → extract). Account queue: the \`mc\` (Mission Control) department.
When you repeat a process for this account — or the user describes THEIR way of doing something —
promote it to an account command with \`/hiveku-new-command\`: it becomes a slash command for every
operator of this account and teaches the dashboard agents. Account-defined commands sync in as
\`/hiveku-<dept>-<slug>\`.
`;
}
